[package]
name = "rs-wgpu-video-player"
version = "0.1.0"
edition = "2021"

[dependencies]
ffmpeg-next = { version = "=8.0.0" }
winit = "0.29.0"
wgpu = "26.0.0"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "sync"] }
